In [1]:
import numpy as np


In [45]:
def function1():

    # create 2d array from 1,12 range 
    # dimension should be 6row 2 columns  
    # and assign this array values in x values in x variable
    # Hint: you can use arange and reshape numpy methods  
    x = np.arange(1,13).reshape(6,2)
    return x
function1()

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [52]:
def function2():
     #create 3D array (3,3,3)
    #must data type should have float64
    #array value should be satart from 10 and end with 36 (both included)
    # Hint: dtype, reshape
    x = np.arange(10,37,dtype=np.float64).reshape((3,3,3))
    return x
function2()

array([[[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]],

       [[19., 20., 21.],
        [22., 23., 24.],
        [25., 26., 27.]],

       [[28., 29., 30.],
        [31., 32., 33.],
        [34., 35., 36.]]])

In [53]:
def function3():
        #extract those numbers from given array. those are must exist in 5,7 Table

    a = np.arange(1,100*10+1).reshape((100,10))
    x = a[a % 35 == 0]
    return x
function3()

array([ 35,  70, 105, 140, 175, 210, 245, 280, 315, 350, 385, 420, 455,
       490, 525, 560, 595, 630, 665, 700, 735, 770, 805, 840, 875, 910,
       945, 980])

In [59]:
def function4():
        #Swap columns 1 and 2 in the array arr.

    arr = np.arange(9).reshape(3,3)
    arr[:,[0, 1]] = arr[:,[1, 0]]
    print(arr)
function4()

[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [61]:
def function5():
        #Create a null vector of size 20 with 4 rows and 5 columns with numpy function

    z = np.zeros(20).reshape((4,5))
    return z
function5()

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [66]:
def function6():
        # Create a null vector of size 10 but the fifth and eighth value which is 10,20 respectively

    arr = np.zeros(10)
    arr[4 ] = 10
    arr[7] = 20
    return arr
function6()

array([ 0.,  0.,  0.,  0., 10.,  0.,  0., 20.,  0.,  0.])

In [76]:
def function7():
        #  Create an array of zeros with the same shape and type as X. Dont use reshape method

    x = np.arange(4, dtype=np.int64)
    a = np.zeros_like(x)
    return a
function7()

array([0, 0, 0, 0], dtype=int64)

In [84]:
def function8():
        # Create a new array of 2x5 uints, filled with 6.

    x = np.full((2,5,),6 , dtype=np.int64)
    return x
function8()

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=int64)

In [96]:
def function9():
        # Create an array of 2, 4, 6, 8, ..., 100.

    a = np.arange(1,100).reshape((99))
    x = a[a % 2 == 0]
    return x
function9()

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [98]:
def function10():
        # Subtract the 1d array brr from the 2d array arr, such that each item of brr subtracts from respective row of arr.

    arr = np.array([[3,3,3],[4,4,4],[5,5,5]])
    brr = np.array([1,2,3])
    subt = arr - np.vstack(brr)
    return subt
function10()

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [119]:
def function11():
        # Replace all odd numbers in arr with -1 without changing arr.

    arr = np.array([0,1,2,3,4,5,6,7,8,9])
    arr[1::2] = -1
    ans = arr
    return ans
function11()


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [102]:
def function12():
    
     # Create the following pattern without hardcoding. Use only numpy functions and the below input array arr.
    # HINT: use stacking concept
    arr = np.array([1,2,3])
    ans = np.hstack((np.repeat(arr, 3),arr,arr,arr))
    return ans
function12()

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [108]:
def function13():
        # Set a condition which gets all items between 5 and 10 from arr.

    arr = np.array([2,6,1,9,10,3,27])
    ans = arr[(arr>5) & (arr<10)]
    return ans
function13()

array([6, 9])

In [107]:
def function14():
      # Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.
    # Hint use split method

    arr = np.arange(10,34,1).reshape(8,3)
    ans = np.split(arr,4)
    return ans
function14()

[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

In [114]:
def function15():
        #Sort following NumPy array by the second column

    arr = np.array([[8,2,-2],[-4,1,7][6,3,9]])
    arr[:3,1:2] = np.sort(arr[:3,1:2] , axis = 0)
    ans = arr
    return ans
function15()

TypeError: list indices must be integers or slices, not tuple

In [111]:
def function16():
        #Write a NumPy program to join a sequence of arrays along depth.

    x = np.array([[1],[2],[3]])
    y = np.array([[2],[3],[4]])
    ans = np.hstack([x,y])
    return ans
function16()

array([[1, 2],
       [2, 3],
       [3, 4]])

In [112]:
def function17():
     # replace numbers with "YES" if it divided by 3 and 5
    # otherwise it will be replaced with "NO"
    # Hint: np.where
    arr = np.arange(1,10*10+1).reshape(10,10)
    return np.where((arr%3==0)&(arr%5==0),"Yes","No")
function17()

array([['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes'],
       ['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes'],
       ['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes'],
       ['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No']],
      dtype='<U3')

In [113]:
def function18():
    # count values of "students" are exist in "piaic"
    piaic = np.arange(100)
    students = np.array([5,20,50,200,301,701])
    x = len(set(piaic)&set(students))
    return x
function18()

3

In [116]:
def function19():
     #Create variable "X" from 1,25 (both are included) range values
    #Convert "X" variable dimension into 5 rows and 5 columns
    #Create one more variable "W" copy of "X" 
    #Swap "W" row and column axis (like transpose)
    # then create variable "b" with value equal to 5
    # Now return output as "(X*W)+b:
    X = np.arange(1,26).reshape(5,5)
    W = X.copy()
    b = 5
    output = (X*W)+b
    return output
function19()
    

array([[  6,   9,  14,  21,  30],
       [ 41,  54,  69,  86, 105],
       [126, 149, 174, 201, 230],
       [261, 294, 329, 366, 405],
       [446, 489, 534, 581, 630]])

In [117]:
def function20():
    #apply fuction "abc" on each value of Array "X"
    x = np.arange(1,11)
    def xyz(x):
        return x*2+3-2
    return xyz(x)
function20()

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])